name: Release add-on
on:
  push:
    tags:
    - '*'
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package and upload
      uses: BigWigsMods/packager@master
      with:
        args: -m pkgmeta.yaml
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
